[sidebar]
emoji = "ðŸŒ²"

[sidebar.avatar]
enabled = true
src = "img/forest.png"
local = true
subtitleKey = "sidebarSubtitle" 

[card]
showDate = false

[article]
showDate = false

[list]
showDate = false
