baseURL = "https://imezhs.eu/" 
title = "iMezhs" 
[[module.imports]]
path = "github.com/CaiJimmy/hugo-theme-stack/v3"

defaultContentLanguage = "lv" 
defaultContentLanguageInSubdir = true 
[languages] 

[languages.lv] 
languageName = "Latviešu" 
languageCode = "lv" 
weight = 1 
[languages.lv.params.sidebar]
subtitle = "Sveiki!"

[languages.lv.menu]

[[languages.lv.menu.main]]
name   = "Blogs"
url    = "/"
weight = 1
params.icon = "tool"  

[languages.ru] 
languageName = "Русский" 
languageCode = "ru" 
weight = 2
[languages.ru.params.sidebar]
subtitle = "привет!"
