baseURL = "https://imezhs.eu/" 
title = "iMezhs" 
[[module.imports]]
path = "github.com/CaiJimmy/hugo-theme-stack/v3"

defaultContentLanguage = "lv" 
defaultContentLanguageInSubdir = true 
[languages] 

[languages.lv] 
languageName = "Latviešu" 
languageCode = "lv" 
weight = 1 

[languages.ru] 
languageName = "Русский" 
languageCode = "ru" 
weight = 2
